export const GET_EVENT_DATA_REQ = "GET_EVENT_DATA_REQ"
export const GET_EVENT_DATA_SUCCESS = "GET_EVENT_DATA_SUCCESS"
export const GET_EVENT_DATA_FAIL = "GET_EVENT_DATA_FAIL"

export const GET_ASSIGNMENT_DATA_REQ = "GET_ASSIGNMENT_DATA_REQ"
export const GET_ASSIGNMENT_DATA_SUCCESS = "GET_ASSIGNMENT_DATA_SUCCESS"
export const GET_ASSIGNMENT_DATA_FAIL = "GET_ASSIGNMENT_DATA_FAIL"

export const ASSIGNMENT_COMPLETE_REQ = "ASSIGNMENT_COMPLETE_REQ"
export const ASSIGNMENT_COMPLETE_SUCCESS = "ASSIGNMENT_COMPLETE_SUCCESS"
export const ASSIGNMENT_COMPLETE_FAIL = "ASSIGNMENT_COMPLETE_FAIL"

