export const LOGIN_REQ = "LOGIN_REQ"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const FACULTY_SIGNUP_REQUEST = "FACULTY_SIGNUP_REQUEST"
export const FACULTY_SIGNUP_SUCCESS = "FACULTY_SIGNUP_SUCCESS"
export const FACULTY_SIGNUP_FAILED = "FACULTY_SIGNUP_FAILED"

export const STUDENT_SIGNUP_REQUEST = "STUDENT_SIGNUP_REQUEST"
export const STUDENT_SIGNUP_SUCCESS = "STUDENT_SIGNUP_SUCCESS"
export const STUDENT_SIGNUP_FAILED = "STUDENT_SIGNUP_FAILED"

export const LOGOUT = "LOGOUT"


export const FACULTY_LOGIN_REQ = "FACULTY_LOGIN_REQ"
export const FACULTY_LOGIN_SUCCESS = "FACULTY_LOGIN_SUCCESS"
export const FACULTY_LOGIN_FAILED = "FACULTY_LOGIN_FAILED"

export const FACULTY_REQ = "FACULTY_REQ"
export const FACULTY_SUCCESS = "FACULTY_SUCCESS"
export const FACULTY_FAILED = "FACULTY_FAILED"

export const FACULTY_LOGOUT = "FACULTY_LOGOUT"



