export const LOGIN_REQ = "LOGIN_REQ"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER_REQ = "REGISTER_REQ"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const LOGOUT = "LOGOUT"


export const FACULTY_LOGIN_REQ = "FACULTY_LOGIN_REQ"
export const FACULTY_LOGIN_SUCCESS = "FACULTY_LOGIN_SUCCESS"
export const FACULTY_LOGIN_FAILED = "FACULTY_LOGIN_FAILED"

export const FACULTY_REQ = "FACULTY_REQ"
export const FACULTY_SUCCESS = "FACULTY_SUCCESS"
export const FACULTY_FAILED = "FACULTY_FAILED"

export const FACULTY_LOGOUT = "FACULTY_LOGOUT"



